site_name: 小程序文档
pages:
    - 换绑新平台 : changeautho.md
    - 手动发布 : publish.md
    - 首页 : index.md
    - 智慧餐厅: dish.md
    - 代理商: agentinfo.md
    - 单页版: single.md
    - 行业版: enterprise.md
    - 专业版: enterprisePro.md
    #    - '小程序管理' : enterprisePro/enterprisePro-appconfig.md
    #    - '小程序编辑' : enterprisePro/
    - 电商版: shop.md
    - 餐饮版: food.md
    - 多门店: multistores.md
    - 同城: city.md
    - 企业版: OfficialWebsite.md
    - 企业智推版  : zhitui.md
plugins:
    - search  
copyright: 小未程序
#theme: readthedocs